version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn

      - run:
          name: Run Linting
          command: yarn lint

      - run:
          name: Run Test Suite
          command: yarn test

      - run:
          name: Build Package
          command: yarn build
